### ISSUE TITLE
stereonet plotting

### ISSUE THREAD

**Issue by tr1813** [karstnet/karstnet#13]
There seems to be a slight mis-handling of dip/azimuth pairs in the generation of graph orientations used for the plotting of a stereonet. This originates in the _set_graph_orientations() method of base.py.

![image](https://github.com/user-attachments/assets/b8a617e6-3d8f-4ad2-b4c6-a2931150b62e)

The sign of negative dips is flipped so all dips are positive, however, concurrently, the azimuth of originally positive dips should be flipped 180° for it to plot correctly on the stereonet.

Example: a caver's shot with gradient 10° to 090° should be recorded as a line with plunge 10° and bearing 270° in the stereonet.
A caver's shot with gradient -10° towards 090° should be recorded as a line with plunge 10° and a bearing of 090° in the stereonet.

Attached are screenshots of the expected behaviour for a cave mostly developed in one bedding plane, dipping about 20° towards 330°, and the stereonet produced by karstnet, which adds "reflected shots". 

![image](https://github.com/user-attachments/assets/00dd4d66-9ce2-4b95-9887-55636e5b6258)

![image](https://github.com/user-attachments/assets/9448f689-c92d-48ec-bebf-c2c419ca9f5c)

**Comment by philipperenard** [comment]
Thank you Tanguy for spotting the problem and proposing a solution as a pull-request.
